alias ll='ls -la'
# Some more alias to avoid making mistakes:
alias rm='rm -v'
alias cp='cp -v'
alias mv='mv -v'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias llw='ls --group-directories-first -lha'